This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./pki.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file pki.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (11 comparisons).
Generating output file pki.acr....done (11 lines written, 0 warnings).
Output written in pki.acr.
Transcript written in pki.alg.
